(function (root) {
  "use strict";
  root.KeiFitDetailDemo = {
    DEFAULT_DEMO_ID: "example-kf-ex-031",
    DEMO_ROWS: [
    {
      id: "example-kf-ex-031",
      demo: true,
      wheelDiameterIn: 15,
      wheelWidthIn: 6.0,
      offsetMm: 28,
      tyreSize: "175/55R15",
      tyreModel: "Example tyre · not a product claim",
      suspension: "Stock",
      wheelModel: "Enkei RPF1 · Example",
      pcd: "4×100",
      hubBoreMm: null,
      hubBoreStatus: "unresolved",
      evidenceConfidence: "Reported",
      ownerReports: 5,
      photos: 4,
      independentSources: 1,
      lastReviewed: "2026-08-12",
      modifications: ["None reported"],
      clearance: {
        outerGuard: "unknown",
        innerGuard: "unknown",
        strut: "unknown",
        brake: "unknown",
        fullLock: "reported-contact",
        compression: "unknown",
        loaded: "unknown",
      },
      clearanceNotes: {
        fullLock: "Owner report notes slight rubbing on full lock (front).",
      },
      unknowns: [
        "Centre bore unresolved",
        "Loaded clearance not documented",
        "Compression clearance not documented",
        "Brake / caliper clearance not documented",
        "Australian tyre/load suitability not verified",
      ],
      evidenceSummary:
        "Documented on Suzuki Carry DA16T by owner reports and photos. Full-lock contact is reported; other clearance conditions remain unverified. Centre bore is unresolved.",
      sources: [
        {
          type: "Owner report",
          vehicle: "Suzuki Carry DA16T · Example",
          setup: "15×6.0 ET +28 · 175/55R15 · Stock",
          suspension: "Stock",
          supports: "Wheel/tyre combo installed on DA16T; notes slight full-lock rub",
          doesNotProve: "Loaded clearance · centre bore · Australian compliance",
          linkLabel: "Original source (placeholder)",
        },
        {
          type: "Photo set",
          vehicle: "Suzuki Carry DA16T · Example",
          setup: "Side / stance photos · Example",
          suspension: "Stock",
          supports: "Visual confirmation of the wheel/tyre package installed",
          doesNotProve: "Full-lock clearance · compression · strut clearance",
          linkLabel: "Original source (placeholder)",
        },
      ],
      relatedIds: ["example-kf-ex-014", "example-kf-ex-088", "example-kf-ex-cand-004"],
    },
    {
      id: "example-kf-ex-014",
      demo: true,
      wheelDiameterIn: 13,
      wheelWidthIn: 5.0,
      offsetMm: 35,
      tyreSize: "165/55R13",
      tyreModel: "Example tyre · not a product claim",
      suspension: "Stock",
      wheelModel: "RAYS TE37 KCR · Example",
      pcd: "4×100",
      hubBoreMm: null,
      hubBoreStatus: "unresolved",
      evidenceConfidence: "Confirmed",
      ownerReports: 3,
      photos: 2,
      independentSources: 2,
      lastReviewed: "2026-07-28",
      modifications: ["None reported"],
      clearance: {
        outerGuard: "unknown",
        innerGuard: "unknown",
        strut: "unknown",
        brake: "unknown",
        fullLock: "unknown",
        compression: "unknown",
        loaded: "unknown",
      },
      clearanceNotes: {},
      unknowns: [
        "Centre bore unresolved",
        "Full-lock clearance not documented",
        "Loaded clearance not documented",
        "Compression clearance not documented",
        "Australian tyre/load suitability not verified",
      ],
      evidenceSummary:
        "Example layout only. Even when a Confirmed label appears for UI reference, clearance conditions stay Unknown unless explicitly documented. Centre bore remains unresolved.",
      sources: [
        {
          type: "Example source",
          vehicle: "Suzuki Carry DA16T · Example",
          setup: "13×5.0 ET +35 · 165/55R13 · Stock",
          suspension: "Stock",
          supports: "Layout reference for a multi-source Confirmed presentation",
          doesNotProve: "Any live clearance claim · centre bore · Australian compliance",
          linkLabel: "Original source (placeholder)",
        },
      ],
      relatedIds: ["example-kf-ex-031", "example-kf-ex-cand-004", "example-kf-ex-088"],
    },
    {
      id: "example-kf-ex-088",
      demo: true,
      wheelDiameterIn: 16,
      wheelWidthIn: 6.5,
      offsetMm: 20,
      tyreSize: "195/45R16",
      tyreModel: "Example tyre · not a product claim",
      suspension: "Lowered",
      wheelModel: "Work Equip 01 · Example",
      pcd: "4×100",
      hubBoreMm: null,
      hubBoreStatus: "unresolved",
      evidenceConfidence: "Unverified",
      ownerReports: 1,
      photos: 0,
      independentSources: 0,
      lastReviewed: "2026-06-02",
      modifications: ["Guard roll / spacer (Example)"],
      clearance: {
        outerGuard: "reported-contact",
        innerGuard: "unknown",
        strut: "reported-contact",
        brake: "unknown",
        fullLock: "unknown",
        compression: "unknown",
        loaded: "unknown",
      },
      clearanceNotes: {
        outerGuard: "Example note: guard contact without mods.",
        strut: "Example note: strut contact without mods.",
      },
      unknowns: [
        "Centre bore unresolved",
        "Full-lock clearance not documented",
        "Loaded clearance not documented",
        "Compression clearance not documented",
        "Brake / caliper clearance not documented",
        "Australian tyre/load suitability not verified",
      ],
      evidenceSummary:
        "Insufficient independent evidence. Contact with guard and strut is reported for this Example setup when unmodified. Treat as a lead only.",
      sources: [
        {
          type: "Owner note",
          vehicle: "Suzuki Carry DA16T · Example",
          setup: "16×6.5 ET +20 · 195/45R16 · Lowered",
          suspension: "Lowered",
          supports: "Reports strut and guard contact without modifications",
          doesNotProve: "Loaded clearance · centre bore · Australian compliance",
          linkLabel: "Original source (placeholder)",
        },
      ],
      relatedIds: ["example-kf-ex-031", "example-kf-ex-014", "example-kf-ex-cand-004"],
    },
    {
      id: "example-kf-ex-cand-004",
      demo: true,
      wheelDiameterIn: 14,
      wheelWidthIn: 5.0,
      offsetMm: 40,
      tyreSize: "155/65R14",
      tyreModel: "Not stated",
      suspension: "Stock",
      wheelModel: "OEM-style steel · Example",
      pcd: "4×100",
      hubBoreMm: null,
      hubBoreStatus: "unresolved",
      evidenceConfidence: "Manufacturer specification",
      ownerReports: 0,
      photos: 0,
      independentSources: 0,
      lastReviewed: "2026-05-18",
      modifications: ["Unknown"],
      clearance: {
        outerGuard: "unknown",
        innerGuard: "unknown",
        strut: "unknown",
        brake: "unknown",
        fullLock: "unknown",
        compression: "unknown",
        loaded: "unknown",
      },
      clearanceNotes: {},
      unknowns: [
        "Centre bore unresolved",
        "Full-lock clearance not documented",
        "Loaded clearance not documented",
        "Compression clearance not documented",
        "Real-world clearance not verified against manufacturer listing",
        "Australian tyre/load suitability not verified",
      ],
      evidenceSummary:
        "Manufacturer documentation may describe a size; real-world clearance on DA16T is still unverified. Centre bore remains unresolved.",
      sources: [
        {
          type: "Manufacturer listing",
          vehicle: "Suzuki Carry DA16T · Example",
          setup: "14×5.0 ET +40 · 155/65R14 · Stock",
          suspension: "Stock",
          supports: "Size appears in manufacturer-style documentation (Example)",
          doesNotProve: "Real-world clearance · centre bore · Australian compliance",
          linkLabel: "Original source (placeholder)",
        },
      ],
      relatedIds: ["example-kf-ex-031", "example-kf-ex-014", "example-kf-ex-088"],
    },
  ]
  };
})(typeof globalThis !== "undefined" ? globalThis : this);
